# Generated by Django 3.2.9 on 2022-01-16 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='nombre')),
                ('expiracion', models.DateTimeField(null=True, verbose_name='expiracion')),
            ],
            options={
                'db_table': 'cupon',
            },
        ),
        migrations.CreateModel(
            name='TipoCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='nombre')),
            ],
            options={
                'db_table': 'tipo_cupon',
            },
        ),
        migrations.CreateModel(
            name='TipoTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='nombre')),
                ('descripcion', models.CharField(default='', max_length=255, verbose_name='descripcion')),
            ],
            options={
                'db_table': 'tipo_tienda',
            },
        ),
        migrations.CreateModel(
            name='CuponGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canjeado', models.BooleanField(default=False, verbose_name='canjeado')),
                ('expiracion', models.DateTimeField(null=True, verbose_name='expiracion')),
                ('fecha_canjeo', models.DateTimeField(null=True, verbose_name='fecha_canjeo')),
                ('cupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='animalfav.cupon', verbose_name='cupon')),
                ('tipo_cupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='animalfav.tipocupon', verbose_name='tipo_cupon')),
            ],
            options={
                'db_table': 'cupon_generado',
            },
        ),
        migrations.AddField(
            model_name='cupon',
            name='tipo_tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='animalfav.tipotienda', verbose_name='tipo_tienda'),
        ),
    ]
