# Generated by Django 3.2.4 on 2022-01-30 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalfav', '0002_evento_recorrido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='ubicación',
            new_name='ubicacion',
        ),
        migrations.RenameField(
            model_name='recorrido',
            old_name='ubicación',
            new_name='ubicacion',
        ),
    ]
