# Generated by Django 3.2.4 on 2022-01-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalfav', '0003_auto_20220130_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorrido',
            name='dia',
        ),
        migrations.AlterField(
            model_name='evento',
            name='dia',
            field=models.CharField(max_length=40),
        ),
    ]
